# .github/workflows/deploy.yml
name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload to Azure Storage
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch \
            --account-name githubstorage001 \
            --destination '$web' \
            --source test \
            --auth-mode key \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }}
